// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebarsSlides = {
  slidesSidebar: [{type: 'autogenerated', dirName: '.'}],
};

module.exports = sidebarsSlides;

